### ISSUE TITLE
Can you simplify the installation?

### ISSUE THREAD

**Issue by jiangtj** [icecory/theme-next-calendar#2]
I saw your comment in https://github.com/theme-next/hexo-theme-next/issues/848
Now, NexT would provide [`theme_inject` filter](https://github.com/theme-next/hexo-theme-next/pull/868) in 7.3.0.
You can see the latest NexT Docs: https://theme-next.org/docs/advanced-settings#Injects
It can simplify the installation.
And you also can submit this to https://github.com/theme-next/awesome-next, share it with others.

**Comment by icecory** [comment]
@jiangtj 我没写过js，对前端这套也不太熟，当初把这个日历移植到next就费了不少劲了😂️，如果你们能支持一下，那就太好了。如果可以的话，直接把找个库移到theme-next就好了。这仓库放在这里，我也没能力推广出去，太可惜了。

**Comment by jiangtj** [comment]
我做了些修改，在https://github.com/theme-next/theme-next-calendar

**Comment by icecory** [comment]
@jiangtj 👍️，这下牛逼了！

**Comment by jiangtj** [comment]
😂 只是把原本要手动移的文件组装起来。。。。
